### PR TITLE
User interface

### PR DESCRIPTION
**Pull request by eduardoreisalvarenga**
Waiting for your comments.

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :game_die: [ Required Changes ] :game_die: 
___
Hi @eduardoreisalvarenga  and @RichardBongani :wave: ,
Nice initiative :clap: . You have followed the git flow properly :clap: .But there are some issues which are blocking me to approve this project. Please follow the instructions below,
___
### :spades: [Mandatory Changes] :spades: 
___
1. You have to setup the linter. Pleae follow this [link](https://github.com/microverseinc/linters-config/tree/master/ruby) to configure linter in this repository.
2. The summary on the PR does not look too much informative. Give a shot to improve it.
3. A loop is needed to get an overview, like how that repetitive task should occur. something like this,
```ruby
game_on = true
# initial instructions for player
while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
___
#### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi team !  

### Nice job! WOW, project looks! :+1: 

### But your project needs a few changes before it can be approved.


*  [REQUIRED] game should inform player if selected move is invalid
*  [REQUIRED] game should inform player if selected move is a winning move
*  [REQUIRED] game should inform player if selected move is a draw move
*  [REQUIRED] game repeats all actions for next player's move

* Linter still not working, kindly recommended to fix it. [Linters](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)


screen
### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes

**Comment by Anna-Myzukina** [comment]
### Amazing! Project looks! :+1: 

## Status [Approved]

I hope in the next projects you can:
screen
* Read more here [Professional Github repository](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
#### Example from Pathwrigt:
Screenshot from 2020-02-04 00-08-38




#### Go ahead and merge to master.
#### Goodluck in your next project Happy coding

**Review by Anna-Myzukina — APPROVED** [review]
Approved

**Pull request merged**
